plugin_names = ['EXAMPLE_splitter']

def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  for plugin_name in plugin_names:
    bld.shlib(
      source = plugin_name + '.cpp',
      target = plugin_name,
      install_path = '${PREFIX}/lib/jubatus/plugin',
      use='JUBATUS_CORE',
      )



  bld(
    rule = 'cp ${SRC} ${TGT}',
    source = 'string_server_config.json',
    target = bld.path.get_bld(),
    )
  bld(
     rule = 'cp ${SRC} ${TGT}',
     source = 'jubaconv_example.sh',
     target = bld.path.get_bld(),
  )
